const express = require('express');
const axios = require('axios');
const app = express();
const PORT = process.env.PORT || 3000;

// --- DỮ LIỆU DỰ ĐOÁN TỪ INPUT CỦA BẠN (Dự đoán KHÔNG NGẪU NHIÊN) ---
const PREDICTION_MAP = {
    "XTXTTXTTXXTXX": "Xỉu",
    "XTXTTXTTXXXTT": "Tài",
    "XTXTTXTTXXXTX": "Tài",
    "XTXTTXTTXXXXT": "Xỉu",
    "XTXTTXTTXXXXX": "Xỉu",
    "XTXTTXTXTTTTT": "Tài",
    "XTXTTXTXTTTTX": "Tài",
    "XTXTTXTXTTTXT": "Xỉu",
    "XTXTTXTXTTTXX": "Xỉu",
    "XTXTTXTXTTXTT": "Tài",
    "XTXTTXTXTTXTX": "Tài",
    "XTXTTXTXTTXXT": "Xỉu",
    "XTXTTXTXTTXXX": "Xỉu",
    "XTXTTXTXTXTTT": "Xỉu",
    "XTXTTXTXTXTTX": "Xỉu",
    "XTXTTXTXTXTXT": "Xỉu",
    "XTXTTXTXTXTXX": "Xỉu",
    "XTXTTXTXTXXTT": "Tài",
    "XTXTTXTXTXXTX": "Tài",
    "XTXTTXTXTXXXT": "Xỉu",
    "XTXTTXTXTXXXX": "Xỉu",
    "XTXTTXTXXTTTT": "Tài",
    "XTXTTXTXXTTTX": "Tài",
    "XTXTTXTXXTTXT": "Xỉu",
    "XTXTTXTXXTTXX": "Xỉu",
    "XTXTTXTXXTXTT": "Tài",
    "XTXTTXTXXTXTX": "Tài",
    "XTXTTXTXXTXXT": "Tài",
    "XTXTTXTXXTXXX": "Tài",
    "XTXTTXTXXXTTT": "Tài",
    "XTXTTXTXXXTTX": "Xỉu",
    "XTXTTXTXXXTXT": "Xỉu",
    "XTXTTXTXXXTXX": "Xỉu",
    "XTXTTXTXXXXTT": "Tài",
    "XTXTTXTXXXXTX": "Tài",
    "XTXTTXTXXXXXT": "Xỉu",
    "XTXTTXTXXXXXX": "Xỉu",
    "XTXTTXXTTTTTT": "Tài",
    "XTXTTXXTTTTTX": "Tài",
    "XTXTTXXTTTTXT": "Xỉu",
    "XTXTTXXTTTTXX": "Xỉu",
    "XTXTTXXTTTXTT": "Tài",
    "XTXTTXXTTTXTX": "Tài",
    "XTXTTXXTTTXXT": "Xỉu",
    "XTXTTXXTTTXXX": "Tài",
    "XTXTTXXTTXTTT": "Xỉu",
    "XTXTTXXTTXTTX": "Xỉu",
    "XTXTTXXTTXTXT": "Xỉu",
    "XTXTTXXTTXTXX": "Xỉu",
    "XTXTTXXTTXXTT": "Tài",
    "XTXTTXXTTXXTX": "Tài",
    "XTXTTXXTTXXXT": "Xỉu",
    "XTXTTXXTTXXXX": "Xỉu",
    "XTXTTXXTXTTTT": "Tài",
    "XTXTTXXTXTTTX": "Tài",
    "XTXTTXXTXTTXT": "Xỉu",
    "XTXTTXXTXTTXX": "Xỉu",
    "XTXTTXXTXTXTT": "Tài",
    "XTXTTXXTXTXTX": "Tài",
    "XTXTTXXTXTXXT": "Tài",
    "XTXTTXXTXTXXX": "Xỉu",
    "XTXTTXXTXXTTT": "Xỉu",
    "XTXTTXXTXXTTX": "Xỉu",
    "XTXTTXXTXXTXT": "Xỉu",
    "XTXTTXXTXXTXX": "Xỉu",
    "XTXTTXXTXXXTT": "Tài",
    "XTXTTXXTXXXTX": "Tài",
    "XTXTTXXTXXXXT": "Xỉu",
    "XTXTTXXTXXXXX": "Xỉu",
    "XTXTTXXXTTTTT": "Tài",
    "XTXTTXXXTTTTX": "Tài",
    "XTXTTXXXTTTXT": "Xỉu",
    "XTXTTXXXTTTXX": "Xỉu",
    "XTXTTXXXTTXTT": "Tài",
    "XTXTTXXXTTXTX": "Tài",
    "XTXTTXXXTTXXT": "Tài",
    "XTXTTXXXTTXXX": "Xỉu",
    "XTXTTXXXTXTTT": "Xỉu",
    "XTXTTXXXTXTTX": "Tài",
    "XTXTTXXXTXTXT": "Xỉu",
    "XTXTTXXXTXTXX": "Xỉu",
    "XTXTTXXXTXXTT": "Tài",
    "XTXTTXXXTXXTX": "Tài",
    "XTXTTXXXTXXXT": "Xỉu",
    "XTXTTXXXTXXXX": "Tài",
    "XTXTTXXXXTTTT": "Tài",
    "XTXTTXXXXTTTX": "Tài",
    "XTXTTXXXXTTXT": "Xỉu",
    "XTXTTXXXXTTXX": "Xỉu",
    "XTXTTXXXXTXTT": "Tài",
    "XTXTTXXXXTXTX": "Tài",
    "XTXTTXXXXTXXT": "Tài",
    "XTXTTXXXXTXXX": "Tài",
    "XTXTTXXXXXTTT": "Tài",
    "XTXTTXXXXXTTX": "Xỉu",
    "XTXTTXXXXXTXT": "Xỉu",
    "XTXTTXXXXXTXX": "Xỉu",
    "XTXTTXXXXXXTT": "Tài",
    "XTXTTXXXXXXTX": "Tài",
    "XTXTTXXXXXXXT": "Xỉu",
    "XTXTTXXXXXXXX": "Xỉu",
    "XTXTXTTTTTTTT": "Tài",
    "XTXTXTTTTTTTX": "Tài",
    "XTXTXTTTTTTXT": "Xỉu",
    "XTXTXTTTTTTXX": "Xỉu",
    "XTXTXTTTTTXTT": "Tài",
    "XTXTXTTTTTXTX": "Tài",
    "XTXTXTTTTTXXT": "Xỉu",
    "XTXTXTTTTTXXX": "Tài",
    "XTXTXTTTTXTTT": "Xỉu",
    "XTXTXTTTTXTTX": "Xỉu",
    "XTXTXTTTTXTXT": "Xỉu",
    "XTXTXTTTTXTXX": "Xỉu",
    "XTXTXTTTTXXTT": "Tài",
    "XTXTXTTTTXXTX": "Tài",
    "XTXTXTTTTXXXT": "Xỉu",
    "XTXTXTTTTXXXX": "Xỉu",
    "XTXTXTTTXTTTT": "Tài",
    "XTXTXTTTXTTTX": "Tài",
    "XTXTXTTTXTTXT": "Xỉu",
    "XTXTXTTTXTTXX": "Xỉu",
    "XTXTXTTTXTXTT": "Tài",
    "XTXTXTTTXTXTX": "Tài",
    "XTXTXTTTXTXXT": "Xỉu",
    "XTXTXTTTXTXXX": "Xỉu",
    "XTXTXTTTXXTTT": "Xỉu",
    "XTXTXTTTXXTTX": "Tài",
    "XTXTXTTTXXTXT": "Xỉu",
    "XTXTXTTTXXTXX": "Xỉu",
    "XTXTXTTTXXXTT": "Tài",
    "XTXTXTTTXXXTX": "Tài",
    "XTXTXTTTXXXXT": "Xỉu",
    "XTXTXTTTXXXXX": "Xỉu",
    "XTXTXTTXTTTTT": "Tài",
    "XTXTXTTXTTTTX": "Tài",
    "XTXTXTTXTTTXT": "Xỉu",
    "XTXTXTTXTTTXX": "Xỉu",
    "XTXTXTTXTTXTT": "Tài",
    "XTXTXTTXTTXTX": "Tài",
    "XTXTXTTXTTXXT": "Xỉu",
    "XTXTXTTXTTXXX": "Xỉu",
    "XTXTXTTXTXTTT": "Xỉu",
    "XTXTXTTXTXTTX": "Xỉu",
    "XTXTXTTXTXTXT": "Xỉu",
    "XTXTXTTXTXTXX": "Xỉu",
    "XTXTXTTXTXXTT": "Tài",
    "XTXTXTTXTXXTX": "Tài",
    "XTXTXTTXTXXXT": "Xỉu",
    "XTXTXTTXTXXXX": "Tài",
    "XTXTXTTXXTTTT": "Tài",
    "XTXTXTTXXTTTX": "Tài",
    "XTXTXTTXXTTXT": "Xỉu",
    "XTXTXTTXXTTXX": "Xỉu",
    "XTXTXTTXXTXTT": "Tài",
    "XTXTXTTXXTXTX": "Tài",
    "XTXTXTTXXTXXT": "Tài",
    "XTXTXTTXXTXXX": "Xỉu",
    "XTXTXTTXXXTTT": "Xỉu",
    "XTXTXTTXXXTTX": "Xỉu",
    "XTXTXTTXXXTXT": "Xỉu",
    "XTXTXTTXXXTXX": "Xỉu",
    "XTXTXTTXXXXTT": "Tài",
    "XTXTXTTXXXXTX": "Tài",
    "XTXTXTTXXXXXT": "Xỉu",
    "XTXTXTTXXXXXX": "Xỉu",
    "XTXTXTXTTTTTT": "Tài",
    "XTXTXTXTTTTTX": "Tài",
    "XTXTXTXTTTTXT": "Xỉu",
    "XTXTXTXTTTTXX": "Xỉu",
    "XTXTXTXTTTXTT": "Tài",
    "XTXTXTXTTTXTX": "Tài",
    "XTXTXTXTTTXXT": "Xỉu",
    "XTXTXTXTTTXXX": "Xỉu",
    "XTXTXTXTTXTTT": "Xỉu",
    "XTXTXTXTTXTTX": "Xỉu",
    "XTXTXTXTTXTXT": "Xỉu",
    "XTXTXTXTTXTXX": "Xỉu",
    "XTXTXTXTTXXTT": "Tài",
    "XTXTXTXTTXXTX": "Tài",
    "XTXTXTXTTXXXT": "Xỉu",
    "XTXTXTXTTXXXX": "Tài",
    "XTXTXTXTXTTTT": "Xỉu",
    "XTXTXTXTXTTTX": "Tài",
    "XTXTXTXTXTTXT": "Xỉu",
    "XTXTXTXTXTTXX": "Xỉu",
    "XTXTXTXTXTXTT": "Tài",
    "XTXTXTXTXTXTX": "Tài",
    "XTXTXTXTXTXXT": "Tài",
    "XTXTXTXTXTXXX": "Tài",
    "XTXTXTXTXXTTT": "Xỉu",
    "XTXTXTXTXXTTX": "Tài",
    "XTXTXTXTXXTXT": "Xỉu",
    "XTXTXTXTXXTXX": "Xỉu",
    "XTXTXTXTXXXTT": "Tài",
    "XTXTXTXTXXXTX": "Tài",
    "XTXTXTXTXXXXT": "Xỉu",
    "XTXTXTXTXXXXX": "Xỉu",
    "XTXTXTXXTTTTT": "Tài",
    "XTXTXTXXTTTTX": "Tài",
    "XTXTXTXXTTTXT": "Xỉu",
    "XTXTXTXXTTTXX": "Xỉu",
    "XTXTXTXXTTXTT": "Tài",
    "XTXTXTXXTTXTX": "Tài",
    "XTXTXTXXTTXXT": "Xỉu",
    "XTXTXTXXTTXXX": "Tài",
    "XTXTXTXXTXTTT": "Xỉu",
    "XTXTXTXXTXTTX": "Tài",
    "XTXTXTXXTXTXT": "Xỉu",
    "XTXTXTXXTXTXX": "Xỉu",
    "XTXTXTXXTXXTT": "Tài",
    "XTXTXTXXTXXTX": "Tài",
    "XTXTXTXXTXXXT": "Xỉu",
    "XTXTXTXXTXXXX": "Xỉu",
    "XTXTXTXXXTTTT": "Xỉu",
    "XTXTXTXXXTTTX": "Tài",
    "XTXTXTXXXTTXT": "Xỉu",
    "XTXTXTXXXTTXX": "Xỉu",
    "XTXTXTXXXTXTT": "Tài",
    "XTXTXTXXXTXTX": "Tài",
    "XTXTXTXXXTXXT": "Xỉu",
    "XTXTXTXXXTXXX": "Tài",
    "XTXTXTXXXXTTT": "Tài",
    "XTXTXTXXXXTTX": "Xỉu",
    "XTXTXTXXXXTXT": "Xỉu",
    "XTXTXTXXXXTXX": "Xỉu",
    "XTXTXTXXXXXTT": "Tài",
    "XTXTXTXXXXXTX": "Tài",
    "XTXTXTXXXXXXT": "Xỉu",
    "XTXTXTXXXXXXX": "Xỉu",
    "XTXTXXTTTTTTT": "Tài",
    "XTXTXXTTTTTTX": "Tài",
    "XTXTXXTTTTTXT": "Xỉu",
    "XTXTXXTTTTTXX": "Xỉu",
    "XTXTXXTTTTXTT": "Tài",
    "XTXTXXTTTTXTX": "Tài",
    "XTXTXXTTTTXXT": "Xỉu",
    "XTXTXXTTTTXXX": "Xỉu",
    "XTXTXXTTTXTTT": "Xỉu",
    "XTXTXXTTTXTTX": "Tài",
    "XTXTXXTTTXTXT": "Xỉu",
    "XTXTXXTTTXTXX": "Xỉu",
    "XTXTXXTTTXXTT": "Tài",
    "XTXTXXTTTXXTX": "Tài",
    "XTXTXXTTTXXXT": "Xỉu",
    "XTXTXXTTTXXXX": "Tài",
    "XTXTXXTTXTTTT": "Tài",
    "XTXTXXTTXTTTX": "Tài",
    "XTXTXXTTXTTXT": "Xỉu",
    "XTXTXXTTXTTXX": "Xỉu",
    "XTXTXXTTXTXTT": "Tài",
    "XTXTXXTTXTXTX": "Tài",
    "XTXTXXTTXTXXT": "Xỉu",
    "XTXTXXTTXTXXX": "Tài",
    "XTXTXXTTXXTTT": "Xỉu",
    "XTXTXXTTXXTTX": "Xỉu",
    "XTXTXXTTXXTXT": "Xỉu",
    "XTXTXXTTXXTXX": "Xỉu",
    "XTXTXXTTXXXTT": "Tài",
    "XTXTXXTTXXXTX": "Tài",
    "XTXTXXTTXXXXT": "Xỉu",
    "XTXTXXTTXXXXX": "Xỉu",
    "XTXTXXTXTTTTT": "Tài",
    "XTXTXXTXTTTTX": "Tài",
    "XTXTXXTXTTTXT": "Xỉu",
    "XTXTXXTXTTTXX": "Xỉu",
    "XTXTXXTXTTXTT": "Tài",
    "XTXTXXTXTTXTX": "Tài",
    "XTXTXXTXTTXXT": "Xỉu",
    "XTXTXXTXTTXXX": "Xỉu",
    "XTXTXXTXTXTTT": "Xỉu",
    "XTXTXXTXTXTTX": "Xỉu",
    "XTXTXXTXTXTXT": "Xỉu",
    "XTXTXXTXTXTXX": "Xỉu",
    "XTXTXXTXTXXTT": "Tài",
    "XTXTXXTXTXXTX": "Tài",
    "XTXTXXTXTXXXT": "Xỉu",
    "XTXTXXTXTXXXX": "Xỉu",
    "XTXTXXTXXTTTT": "Xỉu",
    "XTXTXXTXXTTTX": "Tài",
    "XTXTXXTXXTTXT": "Xỉu",
    "XTXTXXTXXTTXX": "Xỉu",
    "XTXTXXTXXTXTT": "Tài",
    "XTXTXXTXXTXTX": "Tài",
    "XTXTXXTXXTXXT": "Xỉu",
    "XTXTXXTXXTXXX": "Tài",
    "XTXTXXTXXXTTT": "Xỉu",
    "XTXTXXTXXXTTX": "Tài",
    "XTXTXXTXXXTXT": "Xỉu",
    "XTXTXXTXXXTXX": "Xỉu",
    "XTXTXXTXXXXTT": "Tài",
    "XTXTXXTXXXXTX": "Tài",
    "XTXTXXTXXXXXT": "Xỉu",
    "XTXTXXTXXXXXX": "Xỉu",
    "XTXTXXXTTTTTT": "Tài",
    "XTXTXXXTTTTTX": "Tài",
    "XTXTXXXTTTTXT": "Xỉu",
    "XTXTXXXTTTTXX": "Xỉu",
    "XTXTXXXTTTXTT": "Tài",
    "XTXTXXXTTTXTX": "Tài",
    "XTXTXXXTTTXXT": "Tài",
    "XTXTXXXTTTXXX": "Tài",
    "XTXTXXXTTXTTT": "Tài",
    "XTXTXXXTTXTTX": "Tài",
    "XTXTXXXTTXTXT": "Xỉu",
    "XTXTXXXTTXTXX": "Xỉu",
    "XTXTXXXTTXXTT": "Tài",
    "XTXTXXXTTXXTX": "Tài",
    "XTXTXXXTTXXXT": "Xỉu",
    "XTXTXXXTTXXXX": "Tài",
    "XTXTXXXTXTTTT": "Tài",
    "XTXTXXXTXTTTX": "Tài",
    "XTXTXXXTXTTXT": "Xỉu",
    "XTXTXXXTXTTXX": "Xỉu",
    "XTXTXXXTXTXTT": "Tài",
    "XTXTXXXTXTXTX": "Tài",
    "XTXTXXXTXTXXT": "Tài",
    "XTXTXXXTXTXXX": "Xỉu",
    "XTXTXXXTXXTTT": "Xỉu",
    "XTXTXXXTXXTTX": "Tài",
    "XTXTXXXTXXTXT": "Xỉu",
    "XTXTXXXTXXTXX": "Xỉu",
    "XTXTXXXTXXXTT": "Tài",
    "XTXTXXXTXXXTX": "Tài",
    "XTXTXXXTXXXXT": "Xỉu",
    "XTXTXXXTXXXXX": "Xỉu",
    "XTXTXXXXTTTTT": "Tài",
    "XTXTXXXXTTTTX": "Tài",
    "XTXTXXXXTTTXT": "Xỉu",
    "XTXTXXXXTTTXX": "Xỉu",
    "XTXTXXXXTTXTT": "Tài",
    "XTXTXXXXTTXTX": "Tài",
    "XTXTXXXXTTXXT": "Tài",
    "XTXTXXXXTTXXX": "Xỉu",
    "XTXTXXXXTXTTT": "Tài",
    "XTXTXXXXTXTTX": "Tài",
    "XTXTXXXXTXTXT": "Xỉu",
    "XTXTXXXXTXTXX": "Xỉu",
    "XTXTXXXXTXXTT": "Tài",
    "XTXTXXXXTXXTX": "Tài",
    "XTXTXXXXTXXXT": "Xỉu",
    "XTXTXXXXTXXXX": "Xỉu",
    "XTXTXXXXXTTTT": "Xỉu",
    "XTXTXXXXXTTTX": "Tài",
    "XTXTXXXXXTTXT": "Xỉu",
    "XTXTXXXXXTTXX": "Xỉu",
    "XTXTXXXXXTXTT": "Tài",
    "XTXTXXXXXTXTX": "Tài",
    "XTXTXXXXXTXXT": "Tài",
    "XTXTXXXXXTXXX": "Xỉu",
    "XTXTXXXXXXTTT": "Tài",
    "XTXTXXXXXXTTX": "Xỉu",
    "XTXTXXXXXXTXT": "Xỉu",
    "XTXTXXXXXXTXX": "Xỉu",
    "XTXTXXXXXXXTT": "Tài",
    "XTXTXXXXXXXTX": "Tài",
    "XTXTXXXXXXXXT": "Xỉu",
    "XTXTXXXXXXXXX": "Xỉu",
    "XTXXTTTTTTTTT": "Tài",
    "XTXXTTTTTTTTX": "Tài",
    "XTXXTTTTTTTXT": "Xỉu",
    "XTXXTTTTTTTXX": "Xỉu",
    "XTXXTTTTTTXTT": "Tài",
    "XTXXTTTTTTXTX": "Tài",
    "XTXXTTTTTTXXT": "Xỉu",
    "XTXXTTTTTTXXX": "Xỉu",
    "XTXXTTTTTXTTT": "Tài",
    "XTXXTTTTTXTTX": "Tài",
    "XTXXTTTTTXTXT": "Xỉu",
    "XTXXTTTTTXTXX": "Xỉu",
    "XTXXTTTTTXXTT": "Tài",
    "XTXXTTTTTXXTX": "Tài",
    "XTXXTTTTTXXXT": "Xỉu",
    "XTXXTTTTTXXXX": "Xỉu",
    "XTXXTTTTXTTTT": "Xỉu",
    "XTXXTTTTXTTTX": "Tài",
    "XTXXTTTTXTTXT": "Xỉu",
    "XTXXTTTTXTTXX": "Xỉu",
    "XTXXTTTTXTXTT": "Tài",
    "XTXXTTTTXTXTX": "Tài",
    "XTXXTTTTXTXXT": "Xỉu",
    "XTXXTTTTXTXXX": "Xỉu",
    "XTXXTTTTXXTTT": "Tài",
    "XTXXTTTTXXTTX": "Xỉu",
    "XTXXTTTTXXTXT": "Xỉu",
    "XTXXTTTTXXTXX": "Xỉu",
    "XTXXTTTTXXXTT": "Tài",
    "XTXXTTTTXXXTX": "Tài",
    "XTXXTTTTXXXXT": "Xỉu",
    "XTXXTTTTXXXXX": "Xỉu",
    "XTXXTTTXTTTTT": "Tài",
    "XTXXTTTXTTTTX": "Tài",
    "XTXXTTTXTTTXT": "Xỉu",
    "XTXXTTTXTTTXX": "Xỉu",
    "XTXXTTTXTTXTT": "Tài",
    "XTXXTTTXTTXTX": "Tài",
    "XTXXTTTXTTXXT": "Xỉu",
    "XTXXTTTXTTXXX": "Xỉu",
    "XTXXTTTXTXTTT": "Xỉu",
    "XTXXTTTXTXTTX": "Tài",
    "XTXXTTTXTXTXT": "Xỉu",
    "XTXXTTTXTXTXX": "Xỉu",
    "XTXXTTTXTXXTT": "Tài",
    "XTXXTTTXTXXTX": "Tài",
    "XTXXTTTXTXXXT": "Xỉu",
    "XTXXTTTXTXXXX": "Tài",
    "XTXXTTTXXTTTT": "Tài",
    "XTXXTTTXXTTTX": "Tài",
    "XTXXTTTXXTTXT": "Xỉu",
    "XTXXTTTXXTTXX": "Xỉu",
    "XTXXTTTXXTXTT": "Tài",
    "XTXXTTTXXTXTX": "Tài",
    "XTXXTTTXXTXXT": "Tài",
    "XTXXTTTXXTXXX": "Tài",
    "XTXXTTTXXXTTT": "Xỉu",
    "XTXXTTTXXXTTX": "Xỉu",
};

// --- CẤU HÌNH ---
const HISTORY_API_URL = 'https://lich-uhnh.onrender.com/api/taixiu';
const HISTORY_LENGTH = 13; 

// --- HÀM TẠO ĐỘ TIN CẬY NGẪU NHIÊN (RANDOM) ---
/**
 * Tạo một giá trị độ tin cậy ngẫu nhiên (RANDOM) từ 65.0% đến 95.0% (hoặc 0.0% nếu không thể dự đoán).
 * @param {string} prediction - Kết quả dự đoán ("Tài", "Xỉu", hoặc "Không xác định").
 * @returns {string} - Giá trị độ tin cậy dưới dạng chuỗi có ký hiệu %.
 */
function getRandomConfidence(prediction) {
  if (prediction === "Không xác định") {
      return "0.0%"; 
  }
  const min = 65.0;
  const max = 95.0;
  // Dùng Math.random() để tạo ra giá trị ngẫu nhiên
  const confidence = Math.random() * (max - min) + min;
  return confidence.toFixed(1) + "%";
}

// --- HÀM DỰ ĐOÁN (KHÔNG NGẪU NHIÊN) ---
/**
 * Thuật toán dự đoán dựa trên tra cứu Deterministic Lookup Map.
 *
 * @param {string} history - Chuỗi 13 kết quả gần nhất ("T" hoặc "X").
 * @returns {string} - Kết quả dự đoán ("Tài" hoặc "Xỉu") hoặc "Không xác định".
 */
function predictFromHistory(history) {
    if (history.length !== HISTORY_LENGTH) {
        return "Lịch sử không đủ độ dài";
    }
    // Tra cứu trực tiếp trong Map. Hoàn toàn không ngẫu nhiên.
    return PREDICTION_MAP[history] || "Không xác định";
}


// --- ENDPOINT DỰ ĐOÁN ---
app.get('/api/lookup_predict', async (req, res) => {
    try {
        const response = await axios.get(HISTORY_API_URL);
        const historyData = Array.isArray(response.data) ? response.data : [response.data];
        
        // Lấy lịch sử 13 phiên gần nhất, chuyển thành T/X
        const recentHistory = historyData
          .slice(0, HISTORY_LENGTH)
          .map(item => item.Ket_qua === 'Tài' ? 'T' : 'X')
          .join('');
        
        // Đảo ngược chuỗi để có thứ tự CŨ nhất -> MỚI nhất (Phù hợp với key bạn cung cấp)
        const predictionKey = recentHistory.split('').reverse().join('');
        
        const currentData = historyData[0];
        const phienTruocInt = parseInt(currentData.Phien);
        const nextSession = phienTruocInt + 1;
        
        // 1. DỰ ĐOÁN (NON-RANDOM)
        const prediction = predictFromHistory(predictionKey);
        
        // 2. ĐỘ TIN CẬY (RANDOM)
        const confidence = getRandomConfidence(prediction); // HOÀN TOÀN NGẪU NHIÊN

        // Tính tổng xúc xắc
        const tongXucXac = currentData.Tong || (parseInt(currentData.Xuc_xac_1) + parseInt(currentData.Xuc_xac_2) + parseInt(currentData.Xuc_xac_3));

        res.json({
            id: "@cskhtoollxk",
            phien_truoc: currentData.Phien,
            xuc_xac: [currentData.Xuc_xac_1, currentData.Xuc_xac_2, currentData.Xuc_xac_3],
            tong_xuc_xac: tongXucXac,
            ket_qua_truoc: currentData.Ket_qua,
            lich_su_tra_cuu: predictionKey,
            phien_sau: nextSession,
            du_doan: prediction,
            do_tin_cay: confidence,
            giai_thich: `sexx`
        });

    } catch (err) {
        console.error(err.message);
        res.status(500).json({
            id: "@cskhtoollxk_random_confidence",
            error: "Lỗi hệ thống hoặc không thể lấy dữ liệu lịch sử từ API ngoài.",
            du_doan: "Không thể dự đoán",
            do_tin_cay: "0.0%",
            giai_thich: "Đang chờ dữ liệu lịch sử hoặc lỗi kết nối API."
        });
    }
});

app.get('/', (req, res) => {
    res.send("Chào mừng đến API dự đoán Tài Xỉu (Random Confidence)! Truy cập /api/lookup_predict để xem dự đoán.");
});

app.listen(PORT, () => console.log(`Server đang chạy trên cổng ${PORT}`));
    

